### PR TITLE
MAVEN-155 add source formatter plugin

### PR DESCRIPTION
**Pull request by gamerson**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@gamerson can you coordinate with @Ithildir? I actually don't see why we need this repo anymore for 7.0.x.

The SF plugin in master for 7.0.x is built with Gradle and includes a Maven and Ant export as well.

I'd like to deprecate this repo in favor of our Gradle way for 7.0.x.

Thx.

**Comment by gamerson** [comment]
The reason we wanted to keep this was for folks migrating from
liferay-maven-plugin that was used in 6.2.  The idea is that they could
just update their pom to simply point to liferay-maven-plugin version 7.0
and still use the  mvn liferay:build-service command, also the
liferay-maven-plugin provided some nice defaults for maven users.  For
example...

Here is the command for liferay-maven-plugin for service builder

mvn liferay:build-service

and here is the required configuration

                        <plugin>
                                <groupId>com.liferay.maven.plugins</groupId>

<artifactId>liferay-maven-plugin</artifactId>

<version>${liferay.maven.plugin.version}</version>
                                <configuration>

<apiBaseDir>${basedir}/../testProject-portlet-service</apiBaseDir>
                                </configuration>
                        </plugin>


And here is the same command using our new SB plugin

mvn com.liferay:com.liferay.portal.tools.service.builder:build-service

and the configuration

                          <plugin>
                                <groupId>com.liferay</groupId>

<artifactId>com.liferay.portal.tools.service.builder</artifactId>
                                <version>1.0.48</version>
                                <configuration>

<apiDirName>../blade.servicebuilder.api/src/main/java</apiDirName>

<beanLocatorUtil>com.liferay.util.bean.PortletBeanLocatorUtil</beanLocatorUtil>

<hbmFileName>src/main/resources/META-INF/module-hbm.xml</hbmFileName>

<implDirName>src/main/java</implDirName>

<inputFileName>service.xml</inputFileName>

<modelHintsFileName>src/main/resources/META-INF/portlet-model-hints.xml</modelHintsFileName>
                                        <osgiModule>true</osgiModule>

<propsUtil>blade.servicebuilder.service.util.PropsUtil</propsUtil>

<resourcesDirName>src/main/resources</resourcesDirName>

<springFileName>src/main/resources/META-INF/spring/module-spring.xml</springFileName>

<springNamespaces>beans,osgi</springNamespaces>

<sqlDirName>src/main/resources/META-INF/sql</sqlDirName>

<sqlFileName>tables.sql</sqlFileName>
                                        <testDirName>src/it</testDirName>
                                </configuration>
                        </plugin>


So if we want to drop the liferay-maven-plugin mojos that now have maven
plugins in platform would we be able to address these two concerns?  1 )
the command is hard to type and remember (as opposed to
liferay:build-service) and 2) the configuration of the new plugin is very
terse and doesn't support maven standards.

Let me know what you think.

On Wed, Oct 28, 2015 at 4:22 PM, Brian Chan <notifications@github.com>
wrote:

> @gamerson <https://github.com/gamerson> can you coordinate with @Ithildir
> <https://github.com/Ithildir>? I actually don't see why we need this repo
> anymore for 7.0.x.
>
> The SF plugin in master for 7.0.x is built with Gradle and includes a
> Maven and Ant export as well.
>
> I'd like to deprecate this repo in favor of our Gradle way for 7.0.x.
>
> Thx.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/brianchandotcom/liferay-maven-support/pull/105#issuecomment-151994494>
> .
>



-- 
Greg Amerson
Liferay Developer Tools
Liferay, Inc. www.liferay.com

**Comment by brianchandotcom** [comment]
@gamerson @Ithildir

What's the POM https://github.com/brianchandotcom/liferay-portal/tree/master/modules/util/portal-tools-service-builder/samples here for?

Can we modify our Gradle things to address Greg's points 1 and 2?

I'd like to consolidate if possible while still giving Greg what he needs.

Thx.

**Comment by Ithildir** [comment]
For point 2, I think it's possible. The pattern that Ray introduced was to have the same hard-coded defaults for Ant/Gradle/Maven in the `*Args` classes. I obviously had to override those defaults in `gradle-plugins` and (in some cases) in the individual plugins, but I guess we could introduce some sensible defaults directly in the tool jars, and move the Gradle ones from `gradle-plugins` to `gradle-plugins-*` (where possible).

For point 1, @gamerson: is it a matter of `groupId` and `artifactId`? Now they are all different Maven plugins.. or that `liferay:` is some kind of alias? Sorry, I don't know so much about Maven yet :cry:

**Comment by gamerson** [comment]
Looks like the "goalPrefix" is what we need.  If you set the "goalPrefix"
to "liferay" it should be able to be invoked using "liferay:build-service".



On Wed, Oct 28, 2015 at 4:58 PM, Andrea Di Giorgi <notifications@github.com>
wrote:

> For point 2, I think it's possible. The pattern that Ray introduced was to
> have the same hard-coded defaults for Ant/Gradle/Maven in the *Args
> classes. I obviously had to override those defaults in gradle-plugins and
> (in some cases) in the individual plugins, but I guess we could introduce
> some sensible defaults directly in the tool jars, and move the Gradle ones
> from gradle-plugins to gradle-plugins-* (where possible).
>
> For point 1, @gamerson <https://github.com/gamerson>: is it a matter of
> groupId and artifactId? Now they are all different Maven plugins.. or
> that liferay: is some kind of alias? Sorry, I don't know so much about
> Maven yet [image: :cry:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/brianchandotcom/liferay-maven-support/pull/105#issuecomment-152008506>
> .
>



-- 
Greg Amerson
Liferay Developer Tools
Liferay, Inc. www.liferay.com

**Comment by gamerson** [comment]
Looks like that is already set!  so nevermind on point1.

On Wed, Oct 28, 2015 at 5:08 PM, Greg Amerson <gregory.amerson@liferay.com>
wrote:

> Looks like the "goalPrefix" is what we need.  If you set the "goalPrefix"
> to "liferay" it should be able to be invoked using "liferay:build-service".
>
>
>
> On Wed, Oct 28, 2015 at 4:58 PM, Andrea Di Giorgi <
> notifications@github.com> wrote:
>
>> For point 2, I think it's possible. The pattern that Ray introduced was
>> to have the same hard-coded defaults for Ant/Gradle/Maven in the *Args
>> classes. I obviously had to override those defaults in gradle-plugins
>> and (in some cases) in the individual plugins, but I guess we could
>> introduce some sensible defaults directly in the tool jars, and move the
>> Gradle ones from gradle-plugins to gradle-plugins-* (where possible).
>>
>> For point 1, @gamerson <https://github.com/gamerson>: is it a matter of
>> groupId and artifactId? Now they are all different Maven plugins.. or
>> that liferay: is some kind of alias? Sorry, I don't know so much about
>> Maven yet [image: :cry:]
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/brianchandotcom/liferay-maven-support/pull/105#issuecomment-152008506>
>> .
>>
>
>
>
> --
> Greg Amerson
> Liferay Developer Tools
> Liferay, Inc. www.liferay.com
>



-- 
Greg Amerson
Liferay Developer Tools
Liferay, Inc. www.liferay.com

**Comment by gamerson** [comment]
So Brian regarding deprecating the liferay-maven-plugin, looks like for
these Mojos there are new replacement plugins in core:

DBBuilderMojo.java
LangBuilderMojo.java
SassToCssBuilderMojo.java
ServiceBuilderMojo.java

However, I don't see new plugins in core that would work for these:

PluginDeployerMojo.java
PluginDirectDeployerMojo.java
ThemeMergeMojo.java
ThumbnailBuilderMojo.java

Is there a plan to introduce new core plugins for these features?


On Wed, Oct 28, 2015 at 5:10 PM, Greg Amerson <gregory.amerson@liferay.com>
wrote:

> Looks like that is already set!  so nevermind on point1.
>
> On Wed, Oct 28, 2015 at 5:08 PM, Greg Amerson <gregory.amerson@liferay.com
> > wrote:
>
>> Looks like the "goalPrefix" is what we need.  If you set the "goalPrefix"
>> to "liferay" it should be able to be invoked using "liferay:build-service".
>>
>>
>>
>> On Wed, Oct 28, 2015 at 4:58 PM, Andrea Di Giorgi <
>> notifications@github.com> wrote:
>>
>>> For point 2, I think it's possible. The pattern that Ray introduced was
>>> to have the same hard-coded defaults for Ant/Gradle/Maven in the *Args
>>> classes. I obviously had to override those defaults in gradle-plugins
>>> and (in some cases) in the individual plugins, but I guess we could
>>> introduce some sensible defaults directly in the tool jars, and move the
>>> Gradle ones from gradle-plugins to gradle-plugins-* (where possible).
>>>
>>> For point 1, @gamerson <https://github.com/gamerson>: is it a matter of
>>> groupId and artifactId? Now they are all different Maven plugins.. or
>>> that liferay: is some kind of alias? Sorry, I don't know so much about
>>> Maven yet [image: :cry:]
>>>
>>> —
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/brianchandotcom/liferay-maven-support/pull/105#issuecomment-152008506>
>>> .
>>>
>>
>>
>>
>> --
>> Greg Amerson
>> Liferay Developer Tools
>> Liferay, Inc. www.liferay.com
>>
>
>
>
> --
> Greg Amerson
> Liferay Developer Tools
> Liferay, Inc. www.liferay.com
>



-- 
Greg Amerson
Liferay Developer Tools
Liferay, Inc. www.liferay.com

**Comment by brianchandotcom** [comment]
We didn't plan on it until now, but we should do it.

Andrea, can you add them? They should be fairly straightforward. You
already did all the hard ones!

Thx.

--
Brian Chan
Chief Software Architect
Liferay, Inc.
Enterprise. Open Source. For Life.
(626) 806-1190

**Comment by Ithildir** [comment]
I didn't do it yet also because these tools are a bit "special":

`ThemeMergeMojo`, I think, copies the `_diffs` dir and merges it with the parent theme. This code was in Ant, and I translated it into a custom Gradle task inside `gradle-plugins`. I can easily move that task to a different plugin, but I'll have to rewrite the same logic for Maven (and Ant?). Maybe it's just better to extract `ThemeMergeMojo` in a separate Maven plugin, right?

The Thumbnail Builder and the Direct Deployer are still in `portal-impl`, and I don't think it'll be very easy to move them to a separate module like we did for SB, SF, etc. So, should Ant and Maven just fork the JVM and call the tools, like `gradle-plugins` does? Then, maybe we should extract `ThumbnailBuilderMojo` and `PluginDirectDeployerMojo` to separate plugins.

`PluginDeployerMojo` is probably just the `deploy` task, I'll have a look!

**Pull request closed without merging**
